### ISSUE TITLE
openssl incompatibility

### ISSUE THREAD

**Issue by slava-vishnyakov** [stargrave/gogost#4]
First of all - thanks a lot for gogost!! (Если не очень понятно - могу на русском написать. По сути пытаемся подписать и openssl отказывается подтверждать подпись)

We are trying to sign a GOST 34.11-94 digest with GOST 34.10-2001, with OpenSSL it works and verifies, but gogost-generated signature isn't being verified.

```go
package main

import (
	"crypto/rand"
	"encoding/base64"
	"encoding/pem"
	"fmt"
	"io/ioutil"
	"log"
	"testing"
	"os/exec"

	"cypherpunks.ru/gogost/gost3410"
)

var privFn = "privateKey.pem"
var openssl = "openssl"
var pubFn = "publicKey.pem"

func checkError(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

func Test3(t *testing.T) {
	digest, err := base64.StdEncoding.DecodeString("1eH8KAwt4FAbv9IJuwhyrDgUY8lLCpG5GG45uJwnXIg=")
	toSignFn := "/tmp/tosign"
	ioutil.WriteFile(toSignFn, digest, 0777)

	// try to sign with gogost

	b, err := ioutil.ReadFile(privFn)
	checkError(err)

	p, _ := pem.Decode(b)
	privateKey := p.Bytes

	c, err := gost3410.NewCurveFromParams(gost3410.CurveParamsGostR34102001CryptoProA)
	checkError(err)

	prv, err := gost3410.NewPrivateKey(c, gost3410.DigestSize(len(digest)), privateKey)
	checkError(err)

	signature, err := prv.SignDigest(digest, rand.Reader)
	checkError(err)

	signatureFn := "/tmp/signature"
	ioutil.WriteFile(signatureFn, signature, 0777)

	// verify with openssl
	out, err := exec.Command(openssl,
		"dgst",
		"-engine", "gost",
		"-verify", pubFn,
		"-signature", signatureFn,
		toSignFn).Output()

	if err != nil || (string(out) != "Verified OK\n") {
		fmt.Println("gogost signature was not verified")
	} else {
		fmt.Println("gogost signature verified OK")
	}

	// try to sign with openssl

	signatureOpenssl, err := exec.Command(openssl, "dgst", "-engine", "gost", "-sign", privFn, toSignFn).Output()
	checkError(err)

	ioutil.WriteFile(signatureFn, signatureOpenssl, 0777)

	// verify with openssl
	out, err = exec.Command(openssl,
		"dgst",
		"-engine", "gost",
		"-verify", pubFn,
		"-signature", signatureFn,
		toSignFn).Output()
	checkError(err)

	if err != nil || (string(out) != "Verified OK\n") {
		fmt.Println("openssl signature was not verified")
	} else {
		fmt.Println("openssl signature verified OK")
	}

}
```

The output of `go test`:

```
gogost signature was not verified
openssl signature verified OK
```

openssl is configured like so:

Open `/etc/openssl/openssl.cnf`:

At the beginning add:

```
openssl_conf = openssl_def
```

At the end add:

```
[openssl_def]
engines = engine_section
[engine_section]
gost = gost_section
[gost_section]
default_algorithms = ALL
engine_id = gost
```

Check:

```
openssl ciphers|tr ':' '\n'|grep GOST
```

Should show:

```
GOST2001-GOST89-GOST89
GOST94-GOST89-GOST89
```

Will appreciate any help! 
Большое спасибо заранее!

**Comment by stargrave** [comment]
Greetings!

* I am worried about ".pem" filenames extension you are reading as a private or private keys. gost3410 library is some kind of low-level: it does not know about anything like ASN.1. NewPrivateKey will success, because privateKey is just a bunch of bytes for it. You have to parse/decode those PEMs manually somehow. For example, for testing purposes you can run either openssl asn1parse, or dumpasn1 to see the structure: as a rule, 32-byte key will be visible and taken for the use in NewPrivateKey.
* GOST standards have problems with exact structure of hashes and signatures structure fixation. For example 34.11-94 standard does not define how digest must be presented (little-endian vs big-endian). The same applies to public and private keys format. I have met many times that most of that incompatibility problems are always related to the format: try to reverse digest, try to split halves of public key, try to reverse each of the halves, try to reverse private key. Once I have implemented compatibility-layer for GOST algorithms on Python: https://github.com/stargrave/pygost/blob/master/pygost/x509.py. As you can see everything is related to bytes "juggling".

I made X.509 (OpenSSL) compatibility layer in pygost, but currently no in gogost, because of lack of time. But I am pretty sure that your problems only with slightly different data formats (and do not forget that NewPrivateKey expects raw 32-byte key (and 64-byte public key), not the PEM Base64 ASN.1 encoded container).

**Comment by slava-vishnyakov** [comment]
Ok, so the first suspect is the .pem file, it looks like this:

```
Bag Attributes
    localKeyID: A3 C1 2B 1A 67 0D 50 61 C2 16 00 99 7F B0 A9 0E ED 8B 41 77
    friendlyName: cp_exported
Key Attributes
    X509v3 Key Usage: 80
-----BEGIN PRIVATE KEY-----
MEU...
..nig=
-----END PRIVATE KEY-----
```

If I am to take this "MEU.....nig=" string and base64 decode it - I get 71 bytes, not 32 bytes as you suggest. Which is probably a suspect. 

The code that we use:

```
	b, err := ioutil.ReadFile(privFn)
	checkError(err)

	p, _ := pem.Decode(b)
	privateKey := p.Bytes
```

`p.Bytes` is also 71 bytes. This is very strange. 

The key was generated in cryptopro (via test provider) website and then passed through p12FromGostCSP and then through `openssl pkcs12 -in p12.pfx -nocerts -out key.pem -nodes`

The biggest problem is that we are trying to integrate with bank and signature produced by `openssl -sign` passes OK, but `gogost` doesn't pass. The bank, however, has a Java-based implementation.  Which makes me think that 71-byte .pem key is not totally absurd. (The public key is 101-bytes)

I tried to take all "substrings" of length 32 from these 71 bytes `p.Bytes[0:32]`, `p.Bytes[1:33]`, etc... I also tried reversing both `signature` (before writing the file) and/or `privateKey` ("substrings" of 32 bytes)... 

Out of ideas currently :) Will be glad for any help :)

**Comment by stargrave** [comment]
"openssl dgst -sign" commands signs not the specified hash, but hash of it. So if you provide "tosign" file, then OpenSSL forcefully hashes it using 34.11-94 and signs the result.

OpenSSL's private keys inside PEM containers are ASN.1 structures. 32-byte key is at the end of that container. So we can just read it from the end, without ASN.1 structure decoding. And that key needs to be reversed (I found it empirically).

    --- main_test.go.orig	2016-11-13 11:59:34.873256000 +0300
    +++ main_test.go	2016-11-13 12:15:35.952251000 +0300
    @@ -10,7 +10,9 @@
        "os/exec"
        "testing"
     
    +	"cypherpunks.ru/gogost/gost28147"
        "cypherpunks.ru/gogost/gost3410"
    +	"cypherpunks.ru/gogost/gost341194"
     )
     
     var privFn = "privateKey.pem"
    @@ -34,14 +36,21 @@
        checkError(err)
     
        p, _ := pem.Decode(b)
    -	privateKey := p.Bytes
    +	privateKey := p.Bytes[len(p.Bytes)-int(gost3410.DigestSize2001):]
    +	for i, j := 0, len(privateKey)-1; i < j; i, j = i+1, j-1 {
    +		privateKey[i], privateKey[j] = privateKey[j], privateKey[i]
    +	}
     
        c, err := gost3410.NewCurveFromParams(gost3410.CurveParamsGostR34102001CryptoProA)
        checkError(err)
     
    -	prv, err := gost3410.NewPrivateKey(c, gost3410.DigestSize(len(digest)), privateKey)
    +	prv, err := gost3410.NewPrivateKey(c, gost3410.DigestSize2001, privateKey)
        checkError(err)
     
    +	h := gost341194.New(&gost28147.GostR3411_94_CryptoProParamSet)
    +	h.Write(digest)
    +	digest = h.Sum(nil)
    +
        signature, err := prv.SignDigest(digest, rand.Reader)
        checkError(err)

**Comment by slava-vishnyakov** [comment]
Excellent! Thank you! That really helps!

**Comment by slava-vishnyakov** [comment]
Just in case anyone stumbles into this
https://github.com/stargrave/gogost/commit/92e0d038de014c8b3eebc0beba3ef9fe906dd8e3
renamed 
`gost3410.DigestSize2001` is renamed to `gost3410.Mode2001`
`gost3410.DigestSize` is renamed to `gost3410.Mode`
