### ISSUE TITLE
Restoring public key algorithm

### ISSUE THREAD

**Issue by dmitriyb** [stargrave/gogost#5]
Hello and thank you for gogost implementation.

I'm trying to implement algorithm for restoring public key from signature (r, s) and message (e) using gogost (34.10) for signing and validation. According to [Standards for Efficient Cryptography](http://www.secg.org/sec1-v2.pdf) 4.1.6 Public Key Recovery Operation we can restore several points R1, R2,... from r (as r is x coordinate) and after that we compute Q1=r^−1*(sR1−eG), Q2=r^−1*(sR2−eG), where G is base point (Bx, By in curve.go code), r^-1 is r modInverse to N (group order, in curve.go it is Q variable), s from (r, s) and e is message. When we have points Q1, Q2,... we could check right after signing if it matches with our given public key.
This algorithm is used in bitcoin crypto implementation. They using libsecp256k1 implementation for signing, so the curve is known: Koblitz curve with default recommended parameters as in [Standards for Efficient Cryptography](http://www.secg.org/sec2-v2.pdf) 2.4.1. But there are some restrictions on values (r, s):
- If r > N, then we set r to r - N
- If s > N/2, then we set s to N - s

Also they using [RFC6979](https://tools.ietf.org/html/rfc6979) for generating a deterministic k value for signing.
I was trying to implement signing with recovery using gogost and got some issues:

1. Not any k gives me a pair of (r, s) so I can recover valid pubkey. I don't know how to calculate  restrictions for arbitrary gost valid curve.
2. I'm wondering if we have some restrictions on (r, s) so not any k would give recoverable pair, then we probably get weaker crypto algorithm.

So maybe you know how can I calculate restrictions for generated (r, s) pair to get recoverable pubkey? For now I'm implementing some workaround: I want to generate (r, s)  iteratively while I get recoverable pair. It seems to be not efficient.
Will this algorithm be corresponding GOST 34.10 despite the fact that there will be (r, s) restrictions?

Links:
[How does recovering pubkey from ecdsa work](http://crypto.stackexchange.com/questions/18105/how-does-recovering-the-public-key-from-an-ecdsa-signature-work)
[ECDSA: (v, r, s)](http://bitcoin.stackexchange.com/questions/38351/ecdsa-v-r-s-what-is-v)
[secp256k1 go implementation](https://github.com/decred/dcrd/blob/master/dcrec/secp256k1/signature.go)

Will appreciate any help!

**Comment by dmitriyb** [comment]
I've looked through the GOST34.10 and have found some differences between signing/verifying operations between it and ECDSA:
In ECDSA we calculate s=k^-1*(z+rd) mod n while in GOST34.10 we calculate s=(rd+kz) mod n, where z is the hash of signing message, d is the private key and n is the subgroup order. As I can see r is calculating similar in both algorithms. So I guess that formula for pubkey recovering which is applicable to ECDSA: Q=r^−1*(sR−eG) will not recover pubkey from GOST34.10 signature.
So I'm trying to figure out how to modify this formula to achieve recovery of a pubkey. But for now I can't even be sure that it is even possible to do with signing operation in GOST34.10.
Maybe you could help to asses the possibility of this.

Thank you!

**Comment by stargrave** [comment]
Greetings! I am really very bad at all those mathematics, so doubt whether I could help you. Only information I have got is RFCs and standard's PDFs, so not aware of any additional point restrictions.

**Comment by dmitriyb** [comment]
Thanks for answer!
Actually I've got the answer on my questuion: http://crypto.stackexchange.com/questions/42134/ecdsa-pubkey-recovery-issue
So if anyone will want to implement recovery procedure using message and signature he will able to do that with formula on given page.
